blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/Ashraf-ISM/100-Days-of-Python-for-Oil-Gas-Subsurface-Analytics/discussions
    about: Ask questions or share ideas here.
